feat(manage-aur): add capability of managing AUR repos
chaotic-cx/chaotic-repository-template pull request #1
Opened 2024-01-20 18:30 UTC by dr460nf1r3

This needs AUR_KEY supplied via CI variables, which contains the AUR SSH key needed. I chose to use a second variable here as the AUR SSH key might not be the same which is used to establish the SSH connection to Redis.

2024-01-21 08:31 UTC, JustTNE requested changes
I highly doubt this is compatible with github actions honestly

2024-01-31 09:42 UTC, dr460nf1r3 commented
Added CI-specific variables so both GitHub Actions/GitLab CI can be supported.

2024-02-05 17:44 UTC, JustTNE requested changes

2024-02-05 17:44 UTC, JustTNE commented on .ci/manage-aur.sh
> +set -x
As discussed, let us use the existing SSH key here instead

2024-02-05 17:44 UTC, JustTNE commented on .ci/manage-aur.sh
> +fi
```suggestion
# CI-specific variables
if [ -v GITLAB_CI ]; then
    _CI_PIPELINE_URL="$CI_PIPELINE_URL"
    _CI_REPOSITORY_URL="${CI_SERVER_URL}/${CI_PROJECT_PATH}/-/commits/${CI_DEFAULT_BRANCH }"
elif [ -v GITHUB_ACTIONS ]; then
    _CI_PIPELINE_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
    _CI_REPOSITORY_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commits/${GITHUB_REF}"
else
    echo "Warning: Supplying pipeline/project details in commit messages is only supported on GitLab CI/GitHub Actions."
fi
```

2024-02-05 17:44 UTC, JustTNE commented on .ci/manage-aur.sh
> +export GIT_SSH_COMMAND="-i /app/key_aur ssh -o StrictHostKeyChecking=accept-new"
As discussed, let us use the existing SSH key here instead

2024-02-05 17:44 UTC, JustTNE commented on .ci/manage-aur.sh
> +        else
useless else

2024-02-05 17:44 UTC, JustTNE commented on .ci/manage-aur.sh
> +            echo "Starting AUR management.."
should not log spam

2024-02-05 17:44 UTC, JustTNE commented on .ci/manage-aur.sh
> +            fi
```suggestion
            # Clone via SSH to allow pushing
            if ! git clone "ssh://aur@aur.archlinux.org/$package.git" "$TMPDIR/aur-push/$package"; then
                echo "Warning: Failed to clone \"$package\" from AUR."
                continue
            fi
```

2024-02-05 17:44 UTC, JustTNE commented on .ci/manage-aur.sh
> +            # Rsync: delete files in the destination that are not in the source. Exclude deleting .CI, exclude copying .git
that kinda makes no sense

```suggestion
            # Rsync: delete files in the destination that are not in the source. Exclude copying .CI and .git
```

2024-02-05 17:44 UTC, JustTNE commented on .ci/manage-aur.sh
> +            fi
```suggestion
            # Only push if there are changes
            if ! git diff --exit-code --quiet; then
                git add .
                if [ -v _CI_COMMITS_URL ]; then
                    git commit -m "chore: update $package" \
                        -m "This commit was automatically generated to reflect changes to this package in another repository." \
                        -m "The changelog for this package can be found at ${_CI_COMMITS_URL}." \
                        -m "Logs of the corresponding pipeline run can be found here: $_CI_PIPELINE_URL."
                else
                    git commit -m "chore: update $package" \
                        -m "This commit was automatically generated to reflect changes to this package in another repository." \
                        -m "Unfortunately, due to a misconfiguration, the URL of the source repository is not available."
                fi
                git push
            else
                echo "No changes detected, skipping!"
                continue
            fi
```

2024-02-05 17:44 UTC, JustTNE commented on .ci/on-commit.sh
>          fi
```suggestion
            .ci/schedule-packages.sh schedule all
            .ci/manage-aur.sh all
        else
            .ci/schedule-packages.sh schedule "${!PACKAGES[@]}"
            .ci/manage-aur.sh "${!PACKAGES[@]}"
        fi
```

2024-02-05 17:44 UTC, JustTNE commented on .github/workflows/chaotic-on-commit.yml
> +  ACCESS_TOKEN: ${{ secrets.AUR_KEY || secrets.AUR_KEY }}
...what?

2024-02-05 17:44 UTC, JustTNE commented on .github/workflows/chaotic-on-commit.yml
> +          AUR_KEY: ${{ secrets.AUR_KEY }}
uhm..

2024-04-16 08:00 UTC, merged